
services:

  mysql:
    image: mysql:8.0
    container_name: mysql_gestionvente
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: gestionvente
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  backend:
    build: ./Backend
    container_name: backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gestionvente
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    networks:
      - app_network
  
  frontend:
    build: ./Frontend
    container_name: frontend
    restart: always
    depends_on:
      backend:
        condition: service_started
    ports:
      - "3000:80"
    networks:
      - app_network

networks:
    app_network:
      driver: bridge

volumes:
  mysql_data:
